### ISSUE TITLE
JSessionID not actually being called.

### ISSUE THREAD

**Issue by iain17** [igm/sockjs-go#45]
For some reason sockjs.Options.JSessionID or Options.cookie is never gets called. From what I gather the client never sends OPTIONS /options, so it never really starts. The GET version of option is called however.

To replicate this situation just run: https://github.com/igm/sockjs-go/blob/master/testserver/server.go and run sockjs-client (https://github.com/sockjs/sockjs-client) with url: /cookie_needed_echo with no extra options. It should set a JSessionID cookie with value dummy.

Any pointers would be very welcome :)

**Comment by UltraNemesis** [comment]
I also hit this issue, but since a open issue already exists, I am not creating a new one. The reason for this is that the GET handler setup for /info$ in handler.go is not being passed the opts.cookie handler. Because of this, if pre-flight request is not necessitated, then the GET request gets called directly and the JSessionID handler will not get called

`newMapping("GET", prefix+"/info$", xhrCors, noCache, opts.info),
`

need to change to

`newMapping("GET", prefix+"/info$", opts.cookie, xhrCors, noCache, opts.info),
`
